spring:
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password:
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
    timeout: 1000
#  网关服务化
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  cloud:
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  security:
    oauth2:
      jwt:
        signingKey: 123456
gateway:
  ignore:
    authentication:
      startWith: /oauth,/open


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.siwanper.gateway
  local:
    # ????????
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # ?????????
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.siwanper.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB

feign:
  okhttp:
    enabled: true