spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://123.57.144.26:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Shi18740961619?}

  security:
    oauth2:
      jwt:
        signingKey: 123456

  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  mvc:
    throw-exception-if-no-handler-found: true


feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.swp.organization
  local:
    # 短時本地緩存，主要用于要求时效较高的配置
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000

logging:
  level:
    com.springboot.cloud: debug
    org.springframework.web: debug
    org.springframework.security: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true