version: '3'
services:
  redis:
    image: redis:alpine
    container_name: nc-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - nc-net
    ports:
      - "6379:6379"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: nc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - nc-net
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: nc-mysql
    restart: always
    networks:
      - nc-net
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Shi18740961619?

networks:
  nc-net:
    external: false