version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: nc-nacos-standalone
    networks:
      - nc-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
    ports:
      - "8848:8848"